# CODELAB 2

a. Buatlah array 2D berdasarkan 6 digit terakhir NIM kalian.

b. Lakukan operasi pertambahan, pengurangan dan perkalian pada matriks yang kalian buat.

c. Ubahlah matriks tersebut menjadi bentuk 1D.

d. Lakukan slicing pada matriks.

In [1]:
import numpy as np

# a. Membuat array 2D berdasarkan 6 digit terakhir NIM
nim_last_six = "311264"
matrix_2d = np.array([[int(nim_last_six[0]), int(nim_last_six[1]), int(nim_last_six[2])],
                      [int(nim_last_six[3]), int(nim_last_six[4]), int(nim_last_six[5])]])

print("Matrix 2D:")
print(matrix_2d)

Matrix 2D:
[[3 1 1]
 [2 6 4]]


In [2]:
# b. Operasi Pertambahan, Pengurangan, dan Perkalian pada Matriks
matrix_add = matrix_2d + matrix_2d
matrix_sub = matrix_2d - matrix_2d
matrix_mul = matrix_2d * matrix_2d

print("\nOperasi Pertambahan:")
print(matrix_add)

print("\nOperasi Pengurangan:")
print(matrix_sub)

print("\nOperasi Perkalian:")
print(matrix_mul)


Operasi Pertambahan:
[[ 6  2  2]
 [ 4 12  8]]

Operasi Pengurangan:
[[0 0 0]
 [0 0 0]]

Operasi Perkalian:
[[ 9  1  1]
 [ 4 36 16]]


In [3]:
# c. Mengubah Matriks 2D menjadi 1D
matrix_1d = matrix_2d.flatten()
print("\nMatriks 1D:")
print(matrix_1d)


Matriks 1D:
[3 1 1 2 6 4]


In [4]:
# d. Slicing Matriks
# Ambil baris pertama
sliced_row = matrix_2d[0, :]
# Ambil kolom pertama
sliced_column = matrix_2d[:, 0]

print("\nSlicing Matriks - Baris Pertama:")
print(sliced_row)

print("\nSlicing Matriks - Kolom Pertama:")
print(sliced_column)


Slicing Matriks - Baris Pertama:
[3 1 1]

Slicing Matriks - Kolom Pertama:
[3 2]
